server:
  port: 8010

user:
  userServicesUrl: http://localhost:8000/


# Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true